# Generated by Django 4.1.3 on 2024-10-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('filt', models.CharField(choices=[('c', 'completed'), ('a', 'active'), ('h', 'has_due_date')], max_length=50)),
            ],
        ),
    ]
