# Generated by Django 4.1.3 on 2024-10-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='filt',
            field=models.CharField(choices=[('a', 'all'), ('c', 'completed'), ('a', 'active'), ('h', 'has_due_date')], max_length=50),
        ),
    ]
