# Generated by Django 4.1.3 on 2024-10-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_list_filt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('filt', models.CharField(choices=[('a', 'all'), ('c', 'completed'), ('a', 'active'), ('h', 'has_due_date')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='filt',
        ),
    ]
