# Generated by Django 4.1.3 on 2024-10-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0003_others_remove_list_add_date_remove_list_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='others',
            old_name='filt',
            new_name='filter',
        ),
    ]
