# Generated by Django 4.1.3 on 2024-10-06 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_rename_filt_others_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(choices=[('a', 'all'), ('c', 'completed'), ('a', 'active')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Others',
        ),
        migrations.AddField(
            model_name='list',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
