# Generated by Django 4.1.3 on 2024-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0005_other_delete_others_list_add_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.AddField(
            model_name='list',
            name='filter',
            field=models.CharField(choices=[('A', 'All'), ('C', 'Completed'), ('U', 'Uncompleted')], default='Uncompleted', max_length=50),
        ),
    ]
