# Generated by Django 4.1.3 on 2024-10-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0006_delete_other_list_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='filter',
        ),
    ]
