# Generated by Django 4.1.3 on 2024-10-17 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0008_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
